# Build settings
gems:
  - jemoji
  - jekyll-paginate

# Site settings
title: "The Nope Box"
description: > # this means to ignore newlines until "email:"
   I say nope, nope, nope.

email: ekuklu@icloud.com
logo: "/assets/images/logo.gif"
float_logo: false # true, false (default)
cover: "/assets/images/background_image.jpg"

name: 'Buğra Ekuklu'
author: 'Buğra Ekuklu'
author_image: "/assets/images/author.jpg"

paginate:	10

url: "http://www.thenopebox.com" # the base hostname & protocol for your site
baseurl: ""

#fill in disqus shortname to use disqus
#disqus: disqus-shortname

#google_analytics: UA-XXXXX-X

# social icons and sharing options
social:
  - icon:	github
    url:	https://github.com/chatatata
    desc:	Fork me on github
    share_url:
    share_title:
    share_link:
