# Build settings
gems:
  - jemoji
  - jekyll-paginate

# Site settings
title: "The Bunker Box"
description: > # this means to ignore newlines until "email:"
   Redundant stories about distributed systems & data architecture

email: ekuklu@icloud.com
logo: "/assets/images/logo.gif"
float_logo: true # true, false (default)
cover: "/assets/images/background_image.jpg"

name: 'Buğra Ekuklu'
author: 'Buğra Ekuklu'
author_image: "/assets/images/author.jpg"

paginate:	10

url: "http://chatatata.github.io" # the base hostname & protocol for your site
baseurl: ""

#fill in disqus shortname to use disqus
#disqus: disqus-shortname

# social icons and sharing options
social:
  - icon:	github
    url:	https://github.com/chatatata
    desc:	Fork me on github
    share_url:
    share_title:
    share_link:
